services:
  teamspeak3:
    container_name: teamspeak3
    restart: unless-stopped
    image: ghcr.io/navystack/teamspeak:3.13.7
    volumes:
      - ./data/:/var/ts3server/
    environment:
      - TIME_ZONE=Asia/Seoul
      - TS3SERVER_LICENSE=accept
    ports:
      - '9987:9987/udp'
      - '10011:10011/tcp'
      - '30033:30033/tcp'
    networks:
      - internal

networks:
  internal:
