name: Docker Image CI

on:
  workflow_dispatch:

env:
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository owner
        run: |
          repo_owner_lowercase=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWERCASE=$repo_owner_lowercase" >> $GITHUB_ENV
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER_LOWERCASE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date in KST
        run: echo "CURRENT_DATE_KST=$(date +'%Y%m%d-%H%M%S' -d '+9 hours')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:nightly-${{ env.CURRENT_DATE_KST }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:${{ env.CURRENT_DATE_KST }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:3.13.7
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:3.13
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:3
            navystack/iventoy:teamspeak:nightly-${{ env.CURRENT_DATE_KST }}
            navystack/iventoy:teamspeak:${{ env.CURRENT_DATE_KST }}
            navystack/iventoy:teamspeak:3.13.7
            navystack/iventoy:teamspeak:3.13
            navystack/iventoy:teamspeak:3
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64, linux/amd64
          outputs: type=image,push=true
        
