name: Docker Image CI (bot)

on:
  workflow_dispatch:

env:
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository owner
        run: |
          repo_owner_lowercase=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWERCASE=$repo_owner_lowercase" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER_LOWERCASE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date in KST
        run: echo "CURRENT_DATE_KST=$(date +'%Y%m%d-%H%M%S' -d '+9 hours')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: bot.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:bot-nightly-${{ env.CURRENT_DATE_KST }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:bot-${{ env.CURRENT_DATE_KST }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:bot-1.0.2
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:bot-1.0
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/teamspeak:bot-1
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          outputs: type=image,push=true
